import Head from 'next/head';

import Home from '@/components/Home';
import Layout from '@/components/Layout/Layout';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </>
  );
}
