import Head from 'next/head';

import MainPage from '@/components/Home';
import Layout from '@/components/Layout/Layout';

export default function HomePage({ products, isError, isLoding }) {
  return (
    <>
      <Head>
        <title>Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainPage products={products} isError={isError} isLoding={isLoding} />
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
  const baseUrl = process.env.BASE_URL;
  let products = [];
  let isError = false;
  let isLoding = true;

  try {
    const res = await fetch(`${baseUrl}/api/products`);
    products = await res.json();
  } catch (error) {
    isError = true;
  } finally {
    isLoding = false;
  }

  return {
    props: {
      products: products,
      isLoding: isLoding,
      isError: isError,
    },
  };
}
